### ISSUE TITLE
Use a cryptographically secure PRNG for generating random pad names

### ISSUE THREAD

**Issue by drebs** [Gared/ep_new_pad#2]
Hello!

Following the [changes on client-side random pad name generation on Etherpad Lite](https://github.com/ether/etherpad-lite/issues/3516), i think this plugin would benefit if it adopted the same changes, because:

* Pad names generated by this plugin would follow the same name style of client-side generation (i.e. 20 random characters including alphanumerical upper/downcase plus `-` and `_`).
* Probability of collisions with newer names generated on outdated or malicious client side would be smaller.

I can propose a merge request, but we'd need to use something different from `window.crypto` for generating cryptographically secure PRNGs, I guess. I am not keen on nodejs, so I'd need some advice on how to go about this. Would [random-number-csprng](https://www.npmjs.com/package/random-number-csprng) be an option?

Thanks for maintaining this plugin!

**Comment by Gared** [comment]
Thx for your feature request. I think it's a good idea to improve the randomness factor, but I'm neither familiar with crypto in nodejs. After searching around a little bit I've found the nodejs crypto library: https://nodejs.org/docs/latest/api/crypto.html
I don't have much time, so I would appreciate if you could open a merge request.

**Comment by drebs** [comment]
Here is a pull request for this: https://github.com/Gared/ep_new_pad/pull/3

I have not tested it because I don't have the proper dev env. Can you please test it and give feedback? Thanks a lot!
